version: '3.1'
services:
  homer:
    image: b4bz/homer
    volumes:
      - ./assets/:/www/assets
    ports:
      - 8080:8080
    environment:
     - UID=1000
     - GID=1000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M